### ISSUE TITLE
Main output source not showing correctly 

### ISSUE THREAD

**Issue by ASchneiderBR** [norihiro/obs-main-view-source#1] opened 2022-04-02 17:37 UTC
Hello @norihiro. 

I was testing your plugin and it seems there are some things not working correctly.

In this example, I've added your plugin source to this scene. Because this scene had some media sources (avatar pictures on the bottom left corner) that goes outside the canvas area, the source was showing those areas from outside the regular output 1080p canvas. So I had to add a crop filter with 0 value in order to remove those exceeding pixels from outside the canvas. It was working fine but out of blue, it stopped. I've recorded this video showing that the main output source was not showing anything in the current scene, when I disable the crop filter, it only showed something inside the filter properties dialog window, not sure what was going on there.

https://user-images.githubusercontent.com/25224882/161394492-9ea589b7-6a21-4523-818e-775ce92caa56.mp4

Not sure how this "exceeding" pixels from the outside of the project standard 1080p canvas would behave in terms of transformation and crop filter settings, since not all scenes has those objects going outside the canvas area...

This is another scene that I had the main output source added, it shows up the scene but not inside the main output source, I think it should be there as well, right? Or you had it coded to hide its own source from itself? 

![image](https://user-images.githubusercontent.com/25224882/161394663-c56dfe2a-c354-4b4d-b88d-525e424972da.png)

Thank you!

**Comment by ASchneiderBR** [comment] 2022-04-02 17:39
Ok, so after removing the source completely and add it again, I can now show you what I mean about the extra content from outside the canvas:

![image](https://user-images.githubusercontent.com/25224882/161394735-73bec9df-84c3-4891-81e2-6aca3605f3e1.png)

Adding a crop filter solves that:

![image](https://user-images.githubusercontent.com/25224882/161394852-ec560f23-eb0f-469e-a6b5-20df951dc02c.png)

**Comment by norihiro** [comment] 2022-04-02 23:48
> Or you had it coded to hide its own source from itself?

Yes, it's an intentional behavior. The main view source itself has to be hidden when rendering itself. Otherwise, it enters an infinite loop; in the main view rendering routine, it calls the main view rendering routine again and again.

Maybe, we can limit the number of nests or just render the previous frame.

**Comment by ASchneiderBR** [comment] 2022-04-03 00:01
Hello.

> Yes, it's an intentional behavior. The main view source itself has to be hidden when rendering itself. Otherwise, it enters an infinite loop; in the main view rendering routine, it calls the main view rendering routine again and again.

Got it, that makes a lot of sense. I think it is a good idea to not show the source main output inside itself.

Thank you.

**Comment by ASchneiderBR** [comment] 2022-04-03 14:23
Hello @norihiro! Thanks for the update. Just tested it and the "exceeding" objects from outside the main view source are still showing:

![image](https://user-images.githubusercontent.com/25224882/161432112-2321adfc-fc97-4b02-8fd8-a5c416f13078.png)



You can see the source is still 1920x1080 but there are objects showing outside the canvas area, not sure if this is correct.

But when you add it to another scene, something wrong start happening: when the crop filter is activated, it now shows objects from another scene, not the current main output...

![image](https://user-images.githubusercontent.com/25224882/161432249-433da1d5-6321-4430-9e16-82a2c3eab5a0.png)

I think you can reproduce this by following this steps:

1. Create 2 scenes
2. Add a media source with a JPG file or similar
3. Drag that source so it is now partially showing in the main canvas and the other part is hidden outside
4. Add a main view source to the same scene, you will see the exceeding parts showing outside the transformation box
5. Now go to the other blank scene
6. Add a reference source to the same main view source, you will see parts of the other scene there
7. Deactivate the crop filter from that source, everything goes to normal but if you change to the other scene, the objects outside the transformation box will show up because of the crop filter is no longer activated.

Here's another example:

https://user-images.githubusercontent.com/25224882/161432593-f7bb936a-a764-44b0-92bc-3a108444c72d.mp4

I think maybe adding a "cop filter" to the current project canvas size would solve that problem :)

Thank you.

**Comment by norihiro** [comment] 2022-04-03 15:43
I think it will be solved if you enable a checkbox `Cache the main view` in the properties of this plugin.

**Comment by ASchneiderBR** [comment] 2022-04-03 20:13
Hello.

The crop issue is solved by enabling `Cache the main view` but there are still problems when using the main output source that is being used on another scene:

![image](https://user-images.githubusercontent.com/25224882/161446483-2c254e29-6306-4f43-9c97-d0a4fc5b4d3e.png)

In this image, I've added the same main output source that is being used on another scene, note that parts or the other scene are showing on the current view. This screenshot is from the current output scene.

Thank you.

**Comment by norihiro** [comment] 2022-04-04 03:15
I cannot reproduce that.
Did you change the blending mode for the Main View Source in the other scene?

I'm suspecting alpha channel is not correctly handled for the image of the white circle.
I modified blending mode when rendering. I think this would be closer to the condition rendering scene-items.
https://dev.azure.com/norihiro0169/obs-plugintemplate/_build/results?buildId=1288&view=artifacts&type=publishedArtifacts
(You can download from three dots (...) in this page.)

**Comment by ASchneiderBR** [comment] 2022-04-04 17:18
Hello. 

> Did you change the blending mode for the Main View Source in the other scene?

No, there are no blending settings on that scene.

I've installed the latest build from your Azure devs.

This problem goes away and the cache setting is changed:

https://user-images.githubusercontent.com/25224882/161596126-cf3e8c01-4b3d-4172-952b-3cbf7f797d98.mp4

This problem is present on other scenes:

![image](https://user-images.githubusercontent.com/25224882/161596181-49c87de4-57ae-4d11-acfd-8757addf3cc1.png)

The only difference I can see is that the problematic scene has a source mirror source (StreamFX) that is mirroring another scene that has your output source source showing there (I know, really confusing haha)

Thanks.

**Comment by ASchneiderBR** [comment] 2022-04-04 17:20
Ok, so not sure what is going on... If I have the main output source activated on a scene, there's another scene that just brakes and shows something weird:

https://user-images.githubusercontent.com/25224882/161597450-d3665139-12b6-4038-a000-225f86053866.mp4

**Comment by norihiro** [comment] 2022-04-05 03:13
The issue is confirmed with simplified scene settings as below.
```
Loaded scenes:
- scene 'Configuracoes':
    - source: 'purple' (color_source_v3)
    - source: 'Main View Source' (net.nagater.obs-main-view-source.source)
- scene 'Conteudo':
    - source: 'Configuracoes' (scene)
```

If `Main View Source` is enabled in the scene `Configuracoes`, another scene `Conteudo` becomes black, where it is expected purple.

The call-stack of the rendering routines will be as below.
- When rendering `Conteudo` (scene)
  - render `Configuracoes` (scene)
    - render `Main View Source` (main-view-source)
      - render `Conteudo` (scene) -- *suspecting this routine failed because the routine was called inside the same routine.*
        - render `Configuracoes` (scene) -- *suspecting this rendering did not happen.*
          - render `purple` (color_source)
          - render `Main View Source` (main-view-source)

Workaround is to add `Dedicated NDI output` to the source `Main View Source` and optionally hide it. This will trigger `Main View Source` to be rendered in off-screen renderer so that the main-view can be rendered correctly.

**Comment by norihiro** [comment] 2022-07-09 14:30
Close since the mentioning PR is merged.

**Closed as completed by norihiro** 2022-07-09 14:30 UTC
